"""
EmbeddingVector entity model
Represents the numerical vector representation of a content chunk
"""
from pydantic import BaseModel
from typing import List
from datetime import datetime


class EmbeddingVector(BaseModel):
    """
    Represents the numerical vector representation of a content chunk,
    generated by the Cohere model
    """
    id: str
    chunk_id: str
    vector: List[float]
    model: str
    timestamp: datetime = datetime.now()

    class Config:
        """Pydantic configuration"""
        json_encoders = {
            datetime: lambda dt: dt.isoformat()
        }

    def __str__(self):
        return f"EmbeddingVector(id={self.id}, chunk_id={self.chunk_id}, model={self.model}, vector_length={len(self.vector)})"

    def __repr__(self):
        return self.__str__()